"""
EcoLens Phase 0 deliverable -- the acquisition QC report (faculty comment C6).

C6 asks the project to document preprocessing, patch generation, spatial
resolution, temporal selection, cloud filtering and quality control. The
evidence for all of that already exists in patches/acquisition_manifest.json
and config.PATCH_LOCATIONS; this script just renders it as a table that can
be read, cited and dropped into the paper.

Writes:
    results/qc_report.csv   one row per CONFIGURED location (acquired or not)
    results/qc_report.md    the same, plus the summary blocks

Everything here is READ-ONLY with respect to the pipeline. It reports what
was recorded; it never recomputes or infers a value. Where the manifest does
not record something, the cell says so rather than guessing -- see the
"scenes tried" note in the generated markdown.

Run:
    python phase0_qc_report.py
"""

import csv
import json
import os
from collections import Counter, defaultdict

from config import (
    PATCH_LOCATIONS,
    METADATA_CATALOG_PATH,
    ACQUISITION_MANIFEST_PATH,
    MAX_WATER_FRACTION,
    MAX_NODATA_FRACTION,
    RESULTS_DIR,
)

MONTHS = ["", "Jan", "Feb", "Mar", "Apr", "May", "Jun",
          "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]

COLUMNS = [
    "id", "ecosystem", "name", "lat", "lon", "status",
    "scene_date", "scene_month", "growing_season", "cloud_cover_pct",
    "water_pct", "nodata_pct", "ndvi_median", "forest_pct",
    "blue_reflectance", "boa_offset",
]


def fmt(v, nd=4):
    if v is None:
        return ""
    if isinstance(v, float):
        return round(v, nd)
    return v


def build_rows():
    manifest = {}
    if os.path.exists(ACQUISITION_MANIFEST_PATH):
        with open(ACQUISITION_MANIFEST_PATH, encoding="utf-8") as f:
            manifest = json.load(f)

    acquired = set()
    if os.path.exists(METADATA_CATALOG_PATH):
        with open(METADATA_CATALOG_PATH, encoding="utf-8") as f:
            for e in json.load(f):
                acquired.add(e.get("base_id", e["id"].split("_p")[0]))

    rows = []
    for loc in PATCH_LOCATIONS:
        lid = loc["id"]
        rec = manifest.get(lid, {})
        cat = rec.get("catalog_entry", {})
        on_disk = os.path.exists(os.path.join("patches", lid + ".npy"))

        if lid in acquired:
            status = "acquired"
        elif rec and not on_disk:
            status = "rejected (patch removed)"
        elif rec:
            status = "assessed, not in catalog"
        else:
            status = "never acquired"

        month = rec.get("scene_month")
        rows.append({
            "id": lid,
            "ecosystem": loc.get("ecosystem", ""),
            "name": loc.get("name", ""),
            "lat": fmt(loc.get("lat"), 4),
            "lon": fmt(loc.get("lon"), 4),
            "status": status,
            "scene_date": (cat.get("scene_date") or "")[:10],
            "scene_month": MONTHS[month] if isinstance(month, int) and 1 <= month <= 12 else "",
            "growing_season": rec.get("growing_season", ""),
            "cloud_cover_pct": fmt(cat.get("cloud_cover_pct"), 2),
            "water_pct": fmt((rec.get("water_fraction") or 0) * 100, 2) if rec.get("water_fraction") is not None else "",
            "nodata_pct": fmt((rec.get("nodata_fraction") or 0) * 100, 2) if rec.get("nodata_fraction") is not None else "",
            "ndvi_median": fmt(rec.get("ndvi_median"), 4),
            "forest_pct": fmt(rec.get("forest_pct"), 2),
            "blue_reflectance": fmt(rec.get("blue_reflectance"), 4),
            "boa_offset": rec.get("boa_offset", ""),
        })
    return rows


def write_csv(rows, path):
    with open(path, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=COLUMNS)
        w.writeheader()
        w.writerows(rows)


def write_md(rows, path):
    acq = [r for r in rows if r["status"] == "acquired"]
    lost = [r for r in rows if r["status"] != "acquired"]

    by_eco = defaultdict(lambda: [0, 0])
    for r in rows:
        by_eco[r["ecosystem"]][1] += 1
        if r["status"] == "acquired":
            by_eco[r["ecosystem"]][0] += 1

    months = Counter(r["scene_month"] for r in acq if r["scene_month"])
    ndvis = [r["ndvi_median"] for r in acq if isinstance(r["ndvi_median"], float)]
    waters = [r["water_pct"] for r in acq if isinstance(r["water_pct"], float)]
    nodatas = [r["nodata_pct"] for r in acq if isinstance(r["nodata_pct"], float)]
    growing = sum(1 for r in acq if r["growing_season"] is True)

    L = []
    L.append("# EcoLens Phase 0 — Acquisition QC report")
    L.append("")
    L.append("Generated by `phase0_qc_report.py` from `patches/acquisition_manifest.json` "
             "and `config.PATCH_LOCATIONS`. Evidence for faculty comment **C6**.")
    L.append("")
    L.append("## Summary")
    L.append("")
    L.append(f"- **{len(acq)} of {len(rows)}** configured locations acquired and QC-passed")
    L.append(f"- QC thresholds enforced: water ≤ {MAX_WATER_FRACTION:.0%}, "
             f"nodata ≤ {MAX_NODATA_FRACTION:.0%}")
    L.append(f"- Growing-season acquisitions: **{growing} / {len(acq)}**")
    if ndvis:
        L.append(f"- NDVI median across acquired patches: "
                 f"min {min(ndvis):.3f}, median {sorted(ndvis)[len(ndvis)//2]:.3f}, max {max(ndvis):.3f}")
    if waters:
        L.append(f"- Water fraction: max {max(waters):.2f} %")
    if nodatas:
        L.append(f"- Nodata fraction (all-band): max {max(nodatas):.2f} %")
    L.append("")
    L.append("### Per ecosystem")
    L.append("")
    L.append("| ecosystem | acquired | configured |")
    L.append("|---|---|---|")
    for eco in sorted(by_eco):
        got, tot = by_eco[eco]
        L.append(f"| {eco} | {got} | {tot} |")
    L.append("")
    L.append("### Acquisition month distribution")
    L.append("")
    L.append("| month | patches |")
    L.append("|---|---|")
    for m in MONTHS[1:]:
        if months.get(m):
            L.append(f"| {m} | {months[m]} |")
    L.append("")
    if lost:
        L.append("### Locations not in the catalog")
        L.append("")
        L.append("| id | ecosystem | name | status | water % | nodata % | NDVI | forest % |")
        L.append("|---|---|---|---|---|---|---|---|")
        for r in lost:
            L.append("| {id} | {ecosystem} | {name} | {status} | {water_pct} | "
                     "{nodata_pct} | {ndvi_median} | {forest_pct} |".format(**r))
        L.append("")
    L.append("## Methodology exceptions to declare alongside these numbers")
    L.append("")
    L.append("1. **Full-year acquisition window.** `SEARCH_DATE_RANGE` covers all of 2024 "
             "rather than a fixed season, so that growing-season ranking has candidates "
             "to choose from at every latitude.")
    L.append("2. **Per-location cloud override.** `mangrove_004` uses a 40 % cloud ceiling "
             "instead of the global bar. Recorded per-location and visible in the catalog "
             "rather than lowering the threshold for all locations.")
    L.append("3. **Climate rasters are 2.5 arc-min (~4.6 km), not 30 s (~1 km).** A "
             "climate cell is therefore wider than a 2.24 km patch: climate is regional "
             "context, never a patch-level measurement.")
    L.append("4. **DEM covers forest locations only.** `elevation_m` / `ruggedness_m` are "
             "unavailable for the other four ecosystems.")
    L.append("5. **WDPA is absent** (token required), so `protected_area` from "
             "`geo_lookups` is null everywhere.")
    L.append("")
    L.append("## Not recorded by the current manifest")
    L.append("")
    L.append("**Scenes tried per location is NOT stored.** `01_acquire_patches.py` ranks up "
             "to `MAX_SCENE_ATTEMPTS` candidate scenes and keeps the first that passes, but "
             "only the winning `scene_id` is written to the manifest. The count of rejected "
             "candidates, and why each was rejected, is printed at run time and then lost. "
             "This column is therefore omitted rather than guessed. Recording it would "
             "strengthen C6 and is a small change to `01`'s manifest write.")
    L.append("")

    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(L) + "\n")


def main():
    os.makedirs(RESULTS_DIR, exist_ok=True)
    rows = build_rows()
    csv_path = os.path.join(RESULTS_DIR, "qc_report.csv")
    md_path = os.path.join(RESULTS_DIR, "qc_report.md")
    write_csv(rows, csv_path)
    write_md(rows, md_path)

    acq = sum(1 for r in rows if r["status"] == "acquired")
    print(f"Wrote {csv_path} and {md_path}")
    print(f"{acq} of {len(rows)} configured locations acquired.")


if __name__ == "__main__":
    main()
